### ISSUE TITLE
cart.module.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [PavelKrysenko/HomeProject#7]
Тут тоже есть регистрация сервиса CartService. Надо ли его тут тоже регистрировать? Обычно, регистрируем сервис в одном модуле.

**Comment by PavelKrysenko** [comment]
CartService является зашареным между всеми модулями, поэтому он содержится в провайдерах каждого модуля. Согласен. Возможно надо было его внести в CommonModule и остальные бы его использовали

**Comment by VZhyrytskiy** [comment]
Да, его надо зарегистрировать в одном shared модуле и подключать этот модуль
